config/routes.rb
Rails.application.routes.draw do
 
  get 'admin' =>'admin#index'
  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  get 'admin/index'
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'

  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :places

  root 'static_pages#home'
  match '/index', to: 'store#index', via: 'get'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
  match '/browse', to: 'static_pages#browse', via: 'get'

end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="learn-more">
    <div class="row">

      <div class="col-md-4">
        <h3>Travel</h3>
        <p>
          From apartments and rooms to treehouses and boats: stay in
          unique spaces in 192 countries.</p>
        <p> <a href="#">See how to travel on Airbnb</a></p>
      </div>

      <div class="col-md-4">
        <h3>Host</h3>
        <p>
          Renting out your unused space could pay your bills or
          fund your next vacation.</p>
        <p><a href="#">Learn more about hosting</a></p>
      </div>

      <div class="col-md-4">
        <h3>Trust and Safety</h3>
        <p>
          From Verified ID to our worldwide customer support team,
          we've got your back.</p>
        <p><a href="#">Learn about trust at Airbnb</a></p>
      </div>
      <p id="footer">
        &copy; 2014,
        All trademarks appearing on this site belong to their respective owners.
      </p>

    </div>
  </div>

</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Rails app", '#', id: "logo" %>
      <nav>
        <ul class="nav pull-left">
          <li><%= link_to "Home",    root_path %></li>
          <li><%= link_to "Help",    help_path %></li>

        </ul>
        <ul class="nav pull-right">
          <li><%= link_to "About",    about_path %></li>
          <li><%= link_to "Contact",    contact_path %></li>
          <li><%= link_to "Browse", browse_path %></li>

          <% if session[:user_id] %>

              <li id="fat-menu" class="dropdown">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  Account <b class="caret"></b>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Orders", "orders_path" %></li>
                  <li><%= link_to "Places", "places_path" %></li>
                  <li><%= link_to "Users", "users_path" %></li>
                  <li class="divider"></li>
                  <li>
                    <%= link_to "Logout", "logout_path", method: :delete %>
                  </li>
                </ul>
              </li>
          <% else %>
              <li><%= link_to "Sign In", "sessions_new_path" %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsApp4PowtorkaApi   <%= yield(:title) %>   </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <%= render 'layouts/shim' %>
</head>
<body class='<%= controller.controller_name %>'>
<%= render 'layouts/header' %>

<div class="container">
  <%= yield %>
  <%= render 'layouts/footer' %>
</div>

</body>
</html>